version: '3.8'
 
services:
  proxy:
    build:
      context: .
    container_name: proxy-server
    env_file:
      - ./.env
    ports:
      - $PROXY_PORT_HOST:$PROXY_PORT
    networks:
      - main-network
    volumes:
      - ./volumes/logs:/etc/nginx/logs
    restart: unless-stopped

networks:
  main-network:
    external: true