/* eslint-disable @typescript-eslint/no-var-requires, sort-keys */

// const exampleSidebar = require('./exampleSidebar');

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  sidebar: [{type: 'autogenerated', dirName: '.'}],
  // exampleSidebar,
}