module.exports.prism = {
  additionalLanguages: [
    'apacheconf',
    'asciidoc',
    'dns-zone',
    'dockerfile',
    'gitignore',
    'java',
    'nginx',
    'powershell',
    'properties',
    'regex',
    'sass',
    'scss',
    'shell',
    'sln',
    'sql',
    'tsconfig',
    'tsx',
    'webmanifest',
  ],
  theme: require('prism-react-renderer/themes/github'),
};
