name: Test website deployment

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
    - '^releases/v[0-9]+.[0-9]+.[0-9]+'
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test website deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install package dependencies
        run: yarn install --immutable

      - name: Test build website
        run: |
          echo "${{ github.ref }}"
          yarn build